# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('time_in', models.CharField(max_length=50)),
            ],
        ),
    ]
