# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_visitorlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorLogs',
            new_name='VisitorLog',
        ),
    ]
