# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161003_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='time_in',
            field=models.DateTimeField(max_length=50),
        ),
    ]
