# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_studentlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlog',
            old_name='student',
            new_name='student_info',
        ),
        migrations.AddField(
            model_name='studentlog',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='student_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='time_in',
            field=models.DateTimeField(null=True),
        ),
    ]
