# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_studentlog_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlog',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
