# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_visitorlog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='C:\\Users\\eUP\\Desktop\\snapLog\\snaplog3\\snaplogcs197/photos/visitor')),
                ('filename', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='photo',
        ),
    ]
