# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20161005_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
