# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
