# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20161006_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='photo',
            field=models.ImageField(null=True, upload_to='student_dir'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='photo',
            field=models.ImageField(null=True, upload_to='visitor_dir'),
        ),
    ]
